[package]
name = "sort_visualiser"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
nannou = "0.10"
shaderc = "0.5"
shrinkwraprs = "0.2.1"
radix = "0.5"
rayon = "1.2"

[features]
shaderc_fix = ["shaderc/build-from-source"]
