[package]
name = "sort_visualiser"
version = "0.1.0"
authors = ["eggmund <joshuacolclough2@googlemail.com>"]
edition = "2018"

[dependencies]
nannou = "0.10"
shaderc = "0.5.1"

[features]
shaderc_fix = ["shaderc/build-from-source"]